Features/vu 13 stripe integrate
vudoan1708-cyber/Punchliner.app pull request #18
Opened 2022-08-27 18:10 UTC by tranqhuy46

- Stripe integration

2022-08-27 22:23 UTC, vudoan1708-cyber requested changes

2022-08-27 22:23 UTC, vudoan1708-cyber commented on backend/src/app.ts
> +  "/v1/stripe/webhook",
@tranqhuy46 Huy, ô thấy v1/payment/... như thế nào? Chả quan trọng đâu, nh tui thấy thích gọi API này là PAPI á :))

2022-08-27 22:23 UTC, vudoan1708-cyber commented on backend/src/controllers/payment.ts
> +const checkoutSuccessHTML: PaymentCheckoutSuccessRequest = async (
tui nghĩ mình k cần render success từ backend đâu, send json cho fe đc k Huy

2022-08-27 22:23 UTC, vudoan1708-cyber commented on backend/src/app.ts
> +  "/v1/stripe/webhook",
à, hay cái endpoint này internal only cho backend để giao tiếp vs stripe v, nếu v thì ignore comment này nghen

2022-08-27 22:23 UTC, vudoan1708-cyber commented on backend/views/checkout-success/index.pug
> +//- index.pug
nếu có thể trả response về thì càng tốt Huy, để FE lo render success message hợp lí hơn

2022-08-28 07:16 UTC, tranqhuy46 commented on backend/src/controllers/payment.ts
> +const checkoutSuccessHTML: PaymentCheckoutSuccessRequest = async (
làm từ FE thì nó hơi nhiều bước, bên STRIPE họ chỉ trả về session_id thôi, ông phải gọi thêm BE để lấy thông tin của customer nữa, nên để BE trả về luôn cho nó tiện, đỡ phải request nhiều lần lên server với ông đỡ phải handle dưới FE nữa Vũ. Cái nào BE handle được thì để BE handle luôn cho FE đỡ Vũ.

2022-08-28 07:17 UTC, tranqhuy46 commented on backend/src/app.ts
> +  "/v1/stripe/webhook",
Không đổi được Vũ, cái này nó là web hook nên để tách ra cũng được, k cần phải gom vô cùng domain payment với mấy thằng khác đâu Vũ, với lại tui cần declare thằng này trước express.json(), do thằng này cần lấy dữ liệu raw ă.

2022-08-28 08:37 UTC, vudoan1708-cyber commented on backend/src/controllers/payment.ts
> +const checkoutSuccessHTML: PaymentCheckoutSuccessRequest = async (
tui check trên clip ô gửi tui r, đâu có info nào mới đâu Huy, chỉ thông báo user thành premium thôi mà.
Ô nhận đc response từ stripe thì có thông tin gì cần thiết cứ gửi về thôi

2022-08-29 15:59 UTC, tranqhuy46 commented on backend/src/controllers/payment.ts
> +const checkoutSuccessHTML: PaymentCheckoutSuccessRequest = async (
không phải Vũ, nghĩa là vầy nè: Stripe họ sẽ tự redirect user về 1 cái đường link mà mình config sẵn, mà tui thấy là họ chỉ truyền vào cái đường link đó 1 param duy nhất là `sesssion_id` thui, nên dưới FE sẽ không đủ thông tin để hiển thị ra, nên dưới FE phải dùng cái session id đó gọi lên BE để lấy thông tin user (chẳng hạn như email) để hiển thị ra. Còn nếu ông nghĩ k cần hiển thị email của user luôn cũng được Vũ, ông cứ làm 1 trang FE đi rùi sau này tui config để Stripe redirect về trang success đó.

2022-08-29 16:53 UTC, vudoan1708-cyber commented on backend/src/controllers/payment.ts
> +const checkoutSuccessHTML: PaymentCheckoutSuccessRequest = async (
tui nghĩ mình cũng chả cần info của user đâu Huy, chỉ cần render basic info nói là successful là xong ha

2022-08-29 16:54 UTC, vudoan1708-cyber commented on backend/src/controllers/payment.ts
> +const checkoutSuccessHTML: PaymentCheckoutSuccessRequest = async (
còn k muốn có thêm thông tin user mình cho cái redirect về trang successful-checkout trên FE, r trang đo sẽ gọi API lấy những info đó cũng đc.

Ô nghĩ s

2022-08-30 15:43 UTC, tranqhuy46 commented on backend/src/controllers/payment.ts
> +const checkoutSuccessHTML: PaymentCheckoutSuccessRequest = async (
oke Vũ, ông cứ làm trang success đi Vũ, sau này deploy lên rùi tui config lại xíu là đc ă

2022-08-30 15:45 UTC, vudoan1708-cyber commented on backend/src/controllers/payment.ts
> +const checkoutSuccessHTML: PaymentCheckoutSuccessRequest = async (
v ô add cònig đó vào đi Huy, để tui tiếp tục làm

2022-08-30 15:46 UTC, vudoan1708-cyber commented on backend/src/controllers/payment.ts
> +const checkoutSuccessHTML: PaymentCheckoutSuccessRequest = async (
chắc khỏi cần gọi API trang mới bây gioqf đâu, đang gấp rút tui cứ render basic mes nói là successful thôi, sau này tính tiếp

2022-08-30 15:56 UTC, tranqhuy46 commented on backend/src/controllers/payment.ts
> +const checkoutSuccessHTML: PaymentCheckoutSuccessRequest = async (
ông cho tui cái đường dẫn dưới FE đi Vũ

2022-08-30 15:57 UTC, vudoan1708-cyber commented on backend/src/controllers/payment.ts
> +const checkoutSuccessHTML: PaymentCheckoutSuccessRequest = async (
tên host + domain + successful-checkout thôi Huy

2022-08-30 15:58 UTC, vudoan1708-cyber commented on backend/src/controllers/payment.ts
> +const checkoutSuccessHTML: PaymentCheckoutSuccessRequest = async (
à thêm cái nữa, ô có stripe account để test mà k cần phải có real card detail k, cho tui xin demo cho client

2022-08-30 16:27 UTC, tranqhuy46 commented on backend/src/controllers/payment.ts
> +const checkoutSuccessHTML: PaymentCheckoutSuccessRequest = async (
ông nhập 4242 hết luôn Vũ, như hình nè 
<img width="1648" alt="image" src="https://user-images.githubusercontent.com/39490493/187490168-1aec5d34-ef24-4089-af1d-91506c8c5129.png">

2022-08-30 16:58 UTC, merged